### ISSUE TITLE
RPC error

### ISSUE THREAD

**Issue by splix** [ethereumproject/emerald-wallet#147]
```
Uncaught (in promise) Error: Cannot read property 'startsWith' of undefined
    at Function.routeToEmerald (src/lib/rpcApi.js:20:13)
    at RpcApi.jsonPost (src/lib/rpcApi.js:57:28)
    at src/lib/rpcApi.js:35:18
    at RpcApi.call (src/lib/rpcApi.js:34:16)
```

**Comment by whilei** [comment]
What actions were you doing when you found this error?

**Comment by splix** [comment]
just standard launch. it maybe related to Electron

**Comment by whilei** [comment]
roger that --- will push just a more verbose error logging
