### ISSUE TITLE
electron package .app can't find module 'follow-redirects'

### ISSUE THREAD

**Issue by whilei** [ethereumproject/emerald-wallet#153]
```
$ npm run start:electron

... 

   fonts/fontawesome-webfont.ttf     166 kB          [emitted]
 fonts/fontawesome-webfont.woff2    77.2 kB          [emitted]
  fonts/fontawesome-webfont.woff      98 kB          [emitted]
             images/etc_logo.png    7.94 kB          [emitted]
                        tests.js    15.4 kB       0  [emitted]         tests
                        index.js    3.79 MB       1  [emitted]  [big]  index
                       index.css    67.7 kB       1  [emitted]         index
                      index.html  304 bytes          [emitted]
App threw an error during load
Error: Cannot find module 'follow-redirects'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/ia/dev/etc/emerald-wallet/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ia/dev/etc/emerald-wallet/electron/downloader.js:1:1)
    at Object.<anonymous> (/Users/ia/dev/etc/emerald-wallet/electron/downloader.js:309:3)
    at Module._compile (module.js:571:32)
    at loader (/Users/ia/dev/etc/emerald-wallet/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ia/dev/etc/emerald-wallet/node_modules/babel-register/lib/node.js:154:7)
```

**Comment by whilei** [comment]
`npm install --save follow-redirects`
