### ISSUE TITLE
dist can't find module '.'

### ISSUE THREAD

**Issue by whilei** [ethereumproject/emerald-wallet#154]
![screen shot 2017-06-20 at 16 39 30](https://user-images.githubusercontent.com/10228550/27357248-1280692a-55d7-11e7-9efc-37f921912e9b.png)

My process for building for dist is:
```bash
npm run package [--all] # build package (important part is out to /app/main.js, I think)
npm run dist [-mwl]
```

Rel #152, #141

**Comment by whilei** [comment]
I'm not sure I'm using `electron-packager` (especially the code @splix wrote for it in `/electron`) appropriately with regard to `electron-builder`.  It seems these packages are designed to accomplish similar tasks... eg
- https://stackoverflow.com/questions/37113815/electron-builder-vs-electron-packager

Happy for any feedback or pointers.

**Comment by elaineo** [comment]
I got stuck there too. This seems like the appropriate solution, but I did not want to change all the imports if there is an easier way: https://github.com/electron-userland/electron-remote/issues/19

**Comment by splix** [comment]
I got this:
```
$ npm run package
Module not found: Error: Can't resolve 'fs' in '/wallet/node_modules/electron'
 @ ./~/electron/index.js 1:9-22
 @ ./src/store/store.js
 @ ./src/index.js
```
Not sure if it's same, but I know how to fix, webpack should have `target: "electron-main"`. Going to update package.json

**Comment by splix** [comment]
I run it as:
```
NODE_ENV=development ./node_modules/.bin/electron -r babel-register -r babel-polyfill .
```
and ui build in another console:
```
node build --for-electron
```

**Comment by elaineo** [comment]
YEAH!!! The second set of commands works. 

The Javascript error was for running
`npm run package`

and then opening "Emerald Wallet" in the `release` folder. When I run the release app, I get this:

<img width="398" alt="screen shot 2017-06-20 at 9 04 03 pm" src="https://user-images.githubusercontent.com/2349487/27366636-3e572ec4-55fc-11e7-9544-2492938da46d.png">

**Comment by whilei** [comment]
I'm at the same point... 
```
NODE_ENV=development ./node_modules/.bin/electron -r babel-register -r babel-polyfill .
```
works for me to run and develop, but from `npm run package` the resulting `Emerald Wallet.app/` gives me the same error as immediately above.

@splix Is there a step we're missing?

**Comment by splix** [comment]
I tracked it down, the problem is in `downloader.js:6`:
```
import unzipper from 'unzip2';
```

This module seems to be incompatible with Electron (which is using modified `fs`). We need to use a different unzipper

**Comment by whilei** [comment]
just some links for research
- https://github.com/electron-userland/electron-packager/issues/217

**Comment by whilei** [comment]
Have tried experimenting with some more webpacking approaches, currently have gotten
```
App threw an error during load
SyntaxError: /Users/ia/dev/etc/emerald-wallet/app/emerald.js: Invalid number (15:15)
  13 |     if (typeof mode === 'function' || typeof mode === 'undefined') {
  14 |         callback = mode;
> 15 |         mode = 0777 & (~process.umask());
     |                ^
  16 |     }
  17 |
  18 |     if (!callback) {
    at Parser.pp$5.raise (/Users/ia/dev/etc/emerald-wallet/node_modules/babylon/lib/index.js:4454:13)
    at Parser.readNumber (/Users/ia/dev/etc/emerald-wallet/node_modules/babylon/lib/index.js:1268:12)
    at Parser.getTokenFromCode (/Users/ia/dev/etc/emerald-wallet/node_modules/babylon/lib/index.js:1102:21)
    at Parser.readToken (/Users/ia/dev/etc/emerald-wallet/node_modules/babylon/lib/index.js:776:19)
    at Parser.<anonymous> (/Users/ia/dev/etc/emerald-wallet/node_modules/babylon/lib/index.js:7214:20)
    at Parser.readToken (/Users/ia/dev/etc/emerald-wallet/node_modules/babylon/lib/index.js:6011:22)
    at Parser.nextToken (/Users/ia/dev/etc/emerald-wallet/node_modules/babylon/lib/index.js:766:19)
    at Parser.next (/Users/ia/dev/etc/emerald-wallet/node_modules/babylon/lib/index.js:691:10)
    at Parser.pp$3.parseMaybeAssign (/Users/ia/dev/etc/emerald-wallet/node_modules/babylon/lib/index.js:3366:10)
    at Parser.parseMaybeAssign (/Users/ia/dev/etc/emerald-wallet/node_modules/babylon/lib/index.js:6415:20)
^C
```
