### ISSUE TITLE
module not found 'fs'

### ISSUE THREAD

**Issue by whilei** [ethereumproject/emerald-wallet#162]
rel #155 

Has happened before and was resolved with `target: 'electron-main'` in webpack config, I think.

```
$ npm run start
...
ERROR in ./~/electron/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/ia/dev/etc/emerald-wallet/node_modules/electron'
 @ ./~/electron/index.js 1:9-22
 @ ./src/store/store.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8000 ./src/index.js
```

**Comment by whilei** [comment]
@r8d8's solve was delete everything and re-clone and build... darklord magic worked for me too

**Comment by whilei** [comment]
nevermind :(. still happening for me on branch `splix/app-config`

**Comment by whilei** [comment]
```
~/dev/etc/emerald-wallet master= ⟠ npm run start:electron

> emerald-wallet@0.1.0 start:electron /Users/ia/dev/etc/emerald-wallet
> npm run build --for-electron && NODE_ENV=development ./node_modules/.bin/electron -r babel-register -r babel-polyfill .


> emerald-wallet@0.1.0 build /Users/ia/dev/etc/emerald-wallet
> node build --no-watch

(node:9497) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Hash: 50553757e440ddf82c41
Time: 23032ms
                           Asset       Size  Chunks                    Chunk Names
  fonts/Roboto-RegularItalic.svg     760 kB          [emitted]  [big]
   fonts/fontawesome-webfont.eot     166 kB          [emitted]
   fonts/fontawesome-webfont.ttf     166 kB          [emitted]
 fonts/fontawesome-webfont.woff2    77.2 kB          [emitted]
  fonts/fontawesome-webfont.woff      98 kB          [emitted]
          fonts/Roboto-Black.eot      22 kB          [emitted]
    fonts/Roboto-BlackItalic.eot    26.6 kB          [emitted]
           fonts/Roboto-Bold.eot    22.3 kB          [emitted]
     fonts/Roboto-BoldItalic.eot      27 kB          [emitted]
          fonts/Roboto-Light.eot    21.9 kB          [emitted]
    fonts/Roboto-LightItalic.eot    27.8 kB          [emitted]
         fonts/Roboto-Medium.eot    22.5 kB          [emitted]
   fonts/Roboto-MediumItalic.eot    27.6 kB          [emitted]
        fonts/Roboto-Regular.eot    22.1 kB          [emitted]
  fonts/Roboto-RegularItalic.eot    26.9 kB          [emitted]
           fonts/Roboto-Thin.eot    21.2 kB          [emitted]
     fonts/Roboto-ThinItalic.eot    27.9 kB          [emitted]
          fonts/Roboto-Black.svg     749 kB          [emitted]  [big]
          fonts/Roboto-Black.ttf     180 kB          [emitted]
    fonts/Roboto-BlackItalic.svg     776 kB          [emitted]  [big]
    fonts/Roboto-BlackItalic.ttf     185 kB          [emitted]
           fonts/Roboto-Bold.svg     756 kB          [emitted]  [big]
           fonts/Roboto-Bold.ttf     170 kB          [emitted]
     fonts/Roboto-BoldItalic.svg     778 kB          [emitted]  [big]
     fonts/Roboto-BoldItalic.ttf     174 kB          [emitted]
          fonts/Roboto-Light.svg     743 kB          [emitted]  [big]
          fonts/Roboto-Light.ttf     179 kB          [emitted]
    fonts/Roboto-LightItalic.svg     768 kB          [emitted]  [big]
    fonts/Roboto-LightItalic.ttf     183 kB          [emitted]
         fonts/Roboto-Medium.svg     753 kB          [emitted]  [big]
         fonts/Roboto-Medium.ttf     179 kB          [emitted]
   fonts/Roboto-MediumItalic.svg     780 kB          [emitted]  [big]
   fonts/Roboto-MediumItalic.ttf     186 kB          [emitted]
        fonts/Roboto-Regular.svg     733 kB          [emitted]  [big]
        fonts/Roboto-Regular.ttf     171 kB          [emitted]
   fonts/fontawesome-webfont.svg     444 kB          [emitted]  [big]
  fonts/Roboto-RegularItalic.ttf     172 kB          [emitted]
           fonts/Roboto-Thin.svg     743 kB          [emitted]  [big]
           fonts/Roboto-Thin.ttf     180 kB          [emitted]
     fonts/Roboto-ThinItalic.svg     774 kB          [emitted]  [big]
     fonts/Roboto-ThinItalic.ttf     185 kB          [emitted]
         fonts/Roboto-Black.woff    90.1 kB          [emitted]
        fonts/Roboto-Black.woff2    65.1 kB          [emitted]
   fonts/Roboto-BlackItalic.woff    98.9 kB          [emitted]
  fonts/Roboto-BlackItalic.woff2    72.6 kB          [emitted]
          fonts/Roboto-Bold.woff    89.2 kB          [emitted]
         fonts/Roboto-Bold.woff2    63.6 kB          [emitted]
    fonts/Roboto-BoldItalic.woff    94.4 kB          [emitted]
   fonts/Roboto-BoldItalic.woff2    68.6 kB          [emitted]
         fonts/Roboto-Light.woff    89.2 kB          [emitted]
        fonts/Roboto-Light.woff2    64.2 kB          [emitted]
   fonts/Roboto-LightItalic.woff    95.3 kB          [emitted]
  fonts/Roboto-LightItalic.woff2    69.8 kB          [emitted]
        fonts/Roboto-Medium.woff    89.7 kB          [emitted]
       fonts/Roboto-Medium.woff2    64.8 kB          [emitted]
  fonts/Roboto-MediumItalic.woff    97.5 kB          [emitted]
 fonts/Roboto-MediumItalic.woff2    71.6 kB          [emitted]
       fonts/Roboto-Regular.woff    89.4 kB          [emitted]
      fonts/Roboto-Regular.woff2    64.2 kB          [emitted]
 fonts/Roboto-RegularItalic.woff    94.6 kB          [emitted]
fonts/Roboto-RegularItalic.woff2    69.3 kB          [emitted]
          fonts/Roboto-Thin.woff    87.8 kB          [emitted]
         fonts/Roboto-Thin.woff2    62.8 kB          [emitted]
    fonts/Roboto-ThinItalic.woff      94 kB          [emitted]
   fonts/Roboto-ThinItalic.woff2    68.1 kB          [emitted]
             images/etc_logo.png    7.94 kB          [emitted]
              images/loading.gif    44.7 kB          [emitted]
                        tests.js    15.4 kB       0  [emitted]         tests
                        index.js    3.86 MB       1  [emitted]  [big]  index
                       index.css    67.7 kB       1  [emitted]         index
                      index.html  304 bytes          [emitted]

ERROR in ./~/electron/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/ia/dev/etc/emerald-wallet/node_modules/electron'
 @ ./~/electron/index.js 1:9-22
 @ ./src/store/store.js
 @ ./src/index.js
App threw an error during load
Error: Cannot find module 'electron-store'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/ia/dev/etc/emerald-wallet/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ia/dev/etc/emerald-wallet/electron/main.js:7:1)
    at Object.<anonymous> (/Users/ia/dev/etc/emerald-wallet/electron/main.js:110:3)
    at Module._compile (module.js:571:32)
    at loader (/Users/ia/dev/etc/emerald-wallet/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ia/dev/etc/emerald-wallet/node_modules/babel-register/lib/node.js:154:7)

```
