### ISSUE TITLE
getRates for fiat exchange not working

### ISSUE THREAD

**Issue by whilei** [ethereumproject/emerald-wallet#169]

**Comment by whilei** [comment]
possibly related console error
```
/Users/ia/dev/etc/emerald-wallet/node_modules/electron/dist/Electron.app/Contents/Resources/electro…:284 Uncaught (in promise) Error: RPC call method must be a string, got:
                    method: undefined,
                    params: undefined,
                    headers: undefined
    at /Users/ia/dev/etc/emerald-wallet/src/lib/rpcApi.js:31:24
    at RpcApi.call (/Users/ia/dev/etc/emerald-wallet/src/lib/rpcApi.js:29:16)
    at callFunction (/Users/ia/dev/etc/emerald-wallet/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:249:18)
    at EventEmitter.<anonymous> (/Users/ia/dev/etc/emerald-wallet/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Users/ia/dev/etc/emerald-wallet/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

**Comment by elaineo** [comment]
yeah, it looks like we are using this for marketApi, without defining market url

```
const remote = global.require('electron').remote;
return remote.getGlobal('rpc');
```
