### ISSUE TITLE
Doesn't start on Windows with selected remote client

### ISSUE THREAD

**Issue by dulanov** [ethereumproject/emerald-wallet#200]
```
[2017-06-29 08:35:48:0661] [info] userData:  C:\Users\dulanov\AppData\Roaming\EmeraldWallet
[2017-06-29 08:35:48:0682] [info] Chain: [type: none, chain: [object Object]]
[2017-06-29 08:35:48:0711] [info] Starting Emerald...
[2017-06-29 08:35:48:0895] [info] use NONE Geth
[2017-06-29 08:35:48:0898] [info] Starting Emerald Connector... [chainId: 62]
[2017-06-29 08:35:48:0919] [info] Download geth.exe from https://github.com/ethereumproject/go-ethereum/releases/download/v3.5.0/geth-classic-win64-v3.5.0.zip to C:\Users\dulanov\AppData\Local\Temp\download-geth.exe-kqtt4f/
[2017-06-29 08:35:51:0489] [info] Starting Emerald Wallet...
[2017-06-29 08:35:53:0492] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:35:53:0493] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:35:53:0494] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:35:53:0494] [error] Unknown network { chain: 'morden', type: 'local' } 62 none
[2017-06-29 08:35:56:0200] [error] Unable to download Geth Error: hash mismatch
    at C:\Users\dulanov\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:9194:110
    at Deferrals.exports.Deferrals.Deferrals._call (C:\Users\dulanov\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:18841:16)
    at C:\Users\dulanov\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:18853:26
    at trampoline (C:\Users\dulanov\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:18819:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (C:\Users\dulanov\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:18851:16)
    at C:\Users\dulanov\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:9189:32
    at C:\Users\dulanov\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:9190:15
    at Pair.verify_unpad_and_check_hash (C:\Users\dulanov\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:9200:15)
    at C:\Users\dulanov\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:3560:25
    at _this.key_manager.pgp_check_not_expired.subkey_material (C:\Users\dulanov\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:3573:15)

[2017-06-29 08:36:10:0613] [info] Save settings { rpcType: 'remote-auto' }
[2017-06-29 08:36:10:0615] [info] Update settings { rpcType: 'remote-auto' }
[2017-06-29 08:36:10:0619] [info] Shutting down Local Connector
[2017-06-29 08:36:10:0622] [info] use REMOTE Geth
[2017-06-29 08:36:10:0623] [info] Starting Emerald Connector... [chainId: 61]
[2017-06-29 08:36:10:0689] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:36:10:0690] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:36:10:0690] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:36:10:0690] [error] Unknown network { chain: 'morden', type: 'local' } 62 none
[2017-06-29 08:36:10:0700] [info] Use RPC URL https://api.gastracker.io/web3
[2017-06-29 08:36:12:0650] [error] Could not match network type to a known type. Network type was: remote
[2017-06-29 08:36:12:0652] [info] Use RPC URL https://mewapi.epool.io
[2017-06-29 08:36:28:0632] [info] Starting Emerald Wallet...
[2017-06-29 08:36:30:0593] [error] Could not match network type to a known type. Network type was: remote
[2017-06-29 08:36:30:0595] [info] Use RPC URL https://mewapi.epool.io
[2017-06-29 08:37:41:0816] [info] Shutting down Local Connector
[2017-06-29 08:37:41:0817] [info] All services are stopped
[2017-06-29 08:37:46:0593] [info] userData:  C:\Users\dulanov\AppData\Roaming\EmeraldWallet
[2017-06-29 08:37:46:0603] [info] Chain: [type: remote-auto, chain: mainnet]
[2017-06-29 08:37:46:0630] [info] Starting Emerald...
[2017-06-29 08:37:46:0692] [info] use REMOTE Geth
[2017-06-29 08:37:46:0695] [info] Starting Emerald Connector... [chainId: 61]
[2017-06-29 08:37:47:0781] [info] Starting Emerald Wallet...
[2017-06-29 08:37:49:0730] [error] Could not match network type to a known type. Network type was: remote
[2017-06-29 08:37:49:0733] [info] Use RPC URL https://mewapi.epool.io
```

**Comment by dulanov** [comment]
```{
	"rpcType": "remote-auto",
	"chain": "mainnet",
	"chainId": 61
}```

**Comment by ChuckSRQ** [comment]
Doesn't work for me either picking remote node with Windows.

**Comment by whilei** [comment]
Have we resolved this issue with the new `asc` sig?

**Comment by whilei** [comment]
Assuming so -- closing unless further notice.
