### ISSUE TITLE
this.setState is not a function

### ISSUE THREAD

**Issue by whilei** [ethereumproject/emerald-wallet#293]
Happens for me on clicking links -- blocks app from transitioning state semi-permanently (until I click around a lot more). Rel #291

![screen shot 2017-07-28 at 16 48 58](https://user-images.githubusercontent.com/10228550/28737654-2625ddb0-73b5-11e7-9a6e-563bbc2a6be7.png)

```
index.js:38300 Uncaught TypeError: this.setState is not a function
    at Object.handleTouchTap [as onTouchTap] (file:///Users/ia/dev/etc/emerald-wallet/app/index.js:38300:18)
    at EnhancedButton._this.handleTouchTap (file:///Users/ia/dev/etc/emerald-wallet/app/index.js:11603:21)
    at Object.ReactErrorUtils.invokeGuardedCallback (file:///Users/ia/dev/etc/emerald-wallet/app/index.js:36388:16)
    at executeDispatch (file:///Users/ia/dev/etc/emerald-wallet/app/index.js:21832:21)
    at Object.executeDispatchesInOrder (file:///Users/ia/dev/etc/emerald-wallet/app/index.js:21855:5)
    at executeDispatchesAndRelease (file:///Users/ia/dev/etc/emerald-wallet/app/index.js:16699:22)
    at executeDispatchesAndReleaseTopLevel (file:///Users/ia/dev/etc/emerald-wallet/app/index.js:16710:10)
    at Array.forEach (native)
    at forEachAccumulated (file:///Users/ia/dev/etc/emerald-wallet/app/index.js:51264:9)
    at Object.processEventQueue (file:///Users/ia/dev/etc/emerald-wallet/app/index.js:16910:7)
```

**Comment by splix** [comment]
can't reproduce

**Comment by whilei** [comment]
Attached: GIF of "clicking errors" -- I wish I could be more descriptive...

I'll try:
Generally: clicking on some things "freeze" the app
Walkthrough GIF:
- I click on "ADD ETC" and get no expected popup; notice the error log then. 
- I click "SEND" and am directed to SEND view (as expected)
- I click "Dashboard" am directed to wallet view with maladjusted CSS formatting
- I click on "Wallets and Tokens" and get same `this.setState` error, and am not redirected to appropriate view.

 
![click-err](https://user-images.githubusercontent.com/10228550/28739602-d927a0a4-73c1-11e7-9a64-3d19c74bc9e6.gif)

**Comment by gagarin55** [comment]
This is the fix:

```
class WalletsTokensButton extends React.Component {

    constructor(props) {
.....
        this.handleTouchTap = this.handleTouchTap.bind(this);
        this.handleRequestClose = this.handleRequestClose.bind(this);
    }
......

```

**Comment by whilei** [comment]
31df66f has helped -- I am now able to navigate 👍 

It seems there are for me still a couple visual elements broken:
- [ ] black circle over the network selection arrow in the nav
- [ ] "+ WALLETS AND TOKENS" button remains visually to appear selected after being un-selected (click button, then click away, below is result)

![screen shot 2017-07-29 at 08 54 32](https://user-images.githubusercontent.com/10228550/28745362-8cbedf7c-743c-11e7-93da-e2c2562a47ce.png)
