### ISSUE TITLE
Cannot set property 'urlGeth' of null

### ISSUE THREAD

**Issue by mateusreis** [ethereumproject/emerald-wallet#300]
Hello, I don't know if it's a bug... but i installed:

EmeraldWallet-mac-v0.3.142-76df821.dmg

On the first open, it runs fine. I can create wallets and transfer an ETC... after I close, I can't access the wallet, this error appears every time I try to open:

Uncaught Exception:
TypeError: Cannot set property 'urlGeth' of null
    at Object.<anonymous> (/Applications/EmeraldWallet.app/Contents/Resources/app.asar/electron/main.js:39:24)
    at Object.<anonymous> (/Applications/EmeraldWallet.app/Contents/Resources/app.asar/electron/main.js:119:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Object.<anonymous> (/Applications/EmeraldWallet.app/Contents/Resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/Applications/EmeraldWallet.app/Contents/Resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:571:32)

**Comment by elaineo** [comment]
https://github.com/ethereumproject/emerald-wallet/issues/305

**Comment by gagarin55** [comment]
Could you, please, try last Mac version from http://builds.etcdevteam.com/, we have updated it.
