### ISSUE TITLE
Uncaught TypeError: Expected [K, V] tuple: m

### ISSUE THREAD

**Issue by whilei** [ethereumproject/emerald-wallet#311]
version: https://github.com/ethereumproject/emerald-wallet/pull/310

wallet electron console:
```
 action @ 10:49:52.142 LAUNCHER/CONFIG
index.js:121479 Uncaught TypeError: Expected [K, V] tuple: m
    at validateEntry (index.js:4191)
    at index.js:3538
    at IterableSeq.__iterateUncached (index.js:1073)
    at seqIterate (index.js:1220)
    at IterableSeq.IndexedSeq.__iterate (index.js:936)
    at FromEntriesSequence.__iterate (index.js:3534)
    at KeyedIterable.mappedSequence.__iterateUncached (index.js:3631)
    at seqIterate (index.js:1220)
    at KeyedIterable.Seq.__iterate (index.js:890)
    at KeyedIterable.forEach (index.js:4997)
```
![screen shot 2017-08-16 at 10 51 20](https://user-images.githubusercontent.com/10228550/29372478-dfd1fb30-8270-11e7-8b66-958daea81b17.png)

wallet logs:
```
~/dev/etc/emerald-wallet gagarin55-styles-refactoring= ⟠ npm run start:electron

> EmeraldWallet@0.4.0 start:electron /Users/ia/dev/etc/emerald-wallet
> NODE_ENV=development ./node_modules/.bin/electron .

[10:49:48:0880] [info] userData:  /Users/ia/Library/Application Support/EmeraldWallet
[10:49:48:0887] [info] Chain: "morden"
[10:49:48:0887] [info] Settings:  { geth: { type: 'none', url: '' },
  chain: 'morden',
  terms: 'v1',
  rpcType: 'local',
  chainId: 62 }
[10:49:49:0067] [info] Starting Emerald...
Installing Devtron from /Users/ia/dev/etc/emerald-wallet/node_modules/devtron
[10:49:49:0267] [info] Run services from ./
[10:49:49:0268] [debug] New Services setup { connector: { launchType: 1, url: 'http://127.0.0.1:1920' },
  geth: { type: 'none', url: '' },
  chain: { name: undefined, id: undefined } }
[10:49:49:0271] [info] Starting Emerald Connector... [chain: {}]
[10:49:49:0272] [debug] Checking if emerald exists: emerald
[10:49:49:0275] [error] Failed to start Services Error: Invalid Geth launch type undefined
    at Promise (/Users/ia/dev/etc/emerald-wallet/electron/services.js:213:20)
    at Services.startGeth (/Users/ia/dev/etc/emerald-wallet/electron/services.js:212:16)
    at Services.start (/Users/ia/dev/etc/emerald-wallet/electron/services.js:83:18)
    at App.app.on (/Users/ia/dev/etc/emerald-wallet/electron/main.js:56:14)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)

[10:49:49:0597] [debug] OK: emerald exists:  emerald
[10:49:49:0603] [debug] Emerald bin: /Users/ia/dev/etc/emerald-wallet/emerald, args: server,--chain,
[10:49:49:0622] [debug] Emerald log target dir: ./logs
[10:49:49:0655] [debug] [emerald] [INFO]	Starting Emerald Connector - v0.9.1
[INFO]	chain set to 'undefined'

[10:49:49:0656] [debug] [emerald] [INFO]	security level set to 'normal'

[10:49:49:0658] [debug] [emerald] thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:329

[10:49:49:0658] [debug] [emerald] stack backtrace:

[10:49:49:0665] [debug] [emerald]    0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace

[10:49:49:0665] [debug] [emerald] 1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook

[10:49:49:0666] [debug] [emerald]    3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt

[10:49:49:0666] [debug] [emerald]    6: rust_begin_unwind
[10:49:49:0667] [debug] [emerald]
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: emerald_core::rpc::start

[10:49:49:0669] [debug] [emerald]   10: emerald::main
  11: __rust_maybe_catch_panic
  12: std::rt::lang_start

[10:49:49:0675] [error] Emerald Connector process exited with code: 101
2017-08-16 10:49:51.688 Electron Helper[36135:10435503] Couldn't set selectedTextBackgroundColor from default ()
[10:49:51:0824] [info] Starting Emerald Wallet...
[10:49:51:0987] [debug] screen null
[10:49:52:0141] [debug] Got launcher config from electron: {"geth":{"type":"none","url":""},"chain":"morden","terms":"v1","rpcType":"local","chainId":62}
```

**Comment by whilei** [comment]
@gagarin55 I found your change e839b29; I'm still getting the same error.

As a temporary workaround I tried adding

```js 
// electron/services.js#L204
        if (typeof this.setup.geth.launchType === 'undefined') {
            this.setup.geth.launchType = LAUNCH_TYPE.AUTO;
        }
```

However, this still yields:

```
~/dev/etc/emerald-wallet gagarin55-styles-refactoring *= ⟠ npm run start:electron

> EmeraldWallet@0.4.0 start:electron /Users/ia/dev/etc/emerald-wallet
> NODE_ENV=development ./node_modules/.bin/electron .

[13:15:10:0871] [info] userData:  /Users/ia/Library/Application Support/EmeraldWallet
[13:15:10:0880] [info] Chain: "morden"
[13:15:10:0880] [info] Settings:  { geth: { type: 'none', url: '' },
  chain: 'morden',
  terms: 'v1',
  rpcType: 'local',
  chainId: 62 }
[13:15:11:0033] [info] Starting Emerald...
Installing Devtron from /Users/ia/dev/etc/emerald-wallet/node_modules/devtron
[13:15:11:0174] [info] Run services from ./
[13:15:11:0175] [debug] New Services setup { connector: { launchType: 1, url: 'http://127.0.0.1:1920' },
  geth: { type: 'none', url: '' },
  chain: { name: undefined, id: undefined } }
[13:15:11:0192] [info] Starting Emerald Connector... [chain: {}]
[13:15:11:0194] [debug] Checking if emerald exists: emerald
[13:15:11:0661] [debug] OK: emerald exists:  emerald
[13:15:11:0669] [debug] Can't find RPC at http://localhost:8545 : FetchError: request to http://localhost:8545 failed, reason: connect ECONNREFUSED 127.0.0.1:8545
[13:15:11:0669] [info] Can't find existing RPC. Try to launch
[13:15:11:0679] [debug] Emerald bin: /Users/ia/dev/etc/emerald-wallet/emerald, args: server,--chain,
[13:15:11:0699] [debug] Emerald log target dir: ./logs
[13:15:11:0717] [debug] geth exists
[13:15:11:0718] [info] Starting Geth... [bin: ./ network: morden, port: 8545]
[13:15:11:0733] [debug] Geth options: [--chain,morden,--rpc,--rpc-port,8545,--rpc-cors-domain,http://localhost:8000,--cache=128,--fast,--log-dir,logs/geth]
[13:15:11:0757] [debug] [emerald] [INFO]	Starting Emerald Connector - v0.9.1
[INFO]	chain set to 'undefined'
[INFO]	security level set to 'normal'
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:329
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: emerald_core::rpc::start
  10: emerald::main
  11: __rust_maybe_catch_panic
  12: std::rt::lang_start

[13:15:11:0774] [debug] Can't find RPC at http://127.0.0.1:8545 : FetchError: request to http://127.0.0.1:8545 failed, reason: connect ECONNREFUSED 127.0.0.1:8545
[13:15:12:0397] [error] Emerald Connector process exited with code: 101
[13:15:13:0419] [debug] Found an RPC at http://127.0.0.1:8545
[13:15:13:0420] [info] Geth is ready
2017-08-16 13:15:15.497 Electron Helper[52737:11311876] Couldn't set selectedTextBackgroundColor from default ()
[13:15:15:0720] [info] Starting Emerald Wallet...
[13:15:16:0007] [debug] screen null
[13:15:16:0124] [debug] Got launcher config from electron: {"geth":{"type":"none","url":""},"chain":"morden","terms":"v1","rpcType":"local","chainId":62}
[13:15:19:0118] [info] Shutting down Local Geth
[13:15:19:0119] [info] Shutting down Local Connector
[13:15:19:0220] [error] geth process exited with code: 0
[13:15:19:0221] [info] All services are stopped

```

Not sure if this is a vault or wallet issue 😕

**Comment by gagarin55** [comment]
Thank you, will investigate this

**Comment by whilei** [comment]
👍 

Just in case helpful, latest error message (from babac45) is now slightly different --

```
~/dev/etc/emerald-wallet gagarin55-styles-refactoring= ⟠ npm run start:electron

> EmeraldWallet@0.4.0 start:electron /Users/ia/dev/etc/emerald-wallet
> NODE_ENV=development ./node_modules/.bin/electron .

[14:22:20:0777] [info] userData:  /Users/ia/Library/Application Support/EmeraldWallet
[14:22:20:0785] [info] Chain: "morden"
[14:22:20:0786] [info] Settings:  { geth: { type: 'none', url: '' },
  chain: 'morden',
  terms: 'v1',
  rpcType: 'local',
  chainId: 62 }
[14:22:20:0986] [info] Starting Emerald...
Installing Devtron from /Users/ia/dev/etc/emerald-wallet/node_modules/devtron
[14:22:21:0405] [info] Run services from ./
[14:22:21:0406] [debug] New Services setup { connector: { launchType: 1, url: 'http://127.0.0.1:1920' },
  geth: { type: 'none', url: '' },
  chain: { name: undefined, id: undefined } }
[14:22:21:0408] [info] Starting Emerald Connector... [chain: {}]
[14:22:21:0409] [debug] Checking if emerald exists: emerald
[14:22:21:0413] [error] Failed to start Services Error: Invalid Geth launch type undefined
    at Promise (/Users/ia/dev/etc/emerald-wallet/electron/services.js:213:20)
    at Services.startGeth (/Users/ia/dev/etc/emerald-wallet/electron/services.js:212:16)
    at Services.start (/Users/ia/dev/etc/emerald-wallet/electron/services.js:84:18)
    at App.app.on (/Users/ia/dev/etc/emerald-wallet/electron/main.js:56:14)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)

[14:22:22:0086] [debug] OK: emerald exists:  emerald
[14:22:22:0099] [debug] Emerald bin: /Users/ia/dev/etc/emerald-wallet/emerald, args: server,--chain,
[14:22:22:0118] [debug] Emerald log target dir: ./logs
[14:22:22:0165] [debug] [emerald] [INFO]	Starting Emerald Connector - v0.9.1
[INFO]	chain set to 'undefined'

[14:22:22:0167] [debug] [emerald] [INFO]	security level set to 'normal'

[14:22:22:0169] [debug] [emerald] thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:329

[14:22:22:0170] [debug] [emerald] stack backtrace:

[14:22:22:0174] [debug] [emerald]    0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook

[14:22:22:0175] [debug] [emerald]    3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt

[14:22:22:0175] [debug] [emerald]    6:
[14:22:22:0176] [debug] [emerald] rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: emerald_core::rpc::start

[14:22:22:0176] [debug] [emerald]   10: emerald::main
  11: __rust_maybe_catch_panic
  12: std::rt::lang_start

[14:22:22:0182] [error] Emerald Connector process exited with code: 101
2017-08-16 14:22:24.327 Electron Helper[68136:12880334] Couldn't set selectedTextBackgroundColor from default ()
[14:22:24:0420] [info] Starting Emerald Wallet...
[14:22:24:0599] [debug] screen null
[14:22:24:0681] [debug] Got launcher config from electron: {"geth":{"type":"none","url":""},"chain":"morden","terms":"v1","rpcType":"local","chainId":62}
[14:22:36:0524] [info] Shutting down Local Connector
[14:22:36:0525] [info] All services are stopped
```

**Comment by gagarin55** [comment]
Just clean `/Users/ia/Library/Application Support/EmeraldWallet`

These errors causing by old settings format persisted on the disk. No good. But migration not implemented.

**Comment by whilei** [comment]
Of course -- sorry I hadn't thought of this sooner myself.
