### ISSUE TITLE
stuck on creating tx with ledger

### ISSUE THREAD

**Issue by splix** [ethereumproject/emerald-wallet#329]
It seems that there is an error during RPC requests to prepare tx sign, maybe on getting nonce. So it never come to Ledger itself and stuck waiting.

**Comment by tapdancemobile** [comment]
I'll see what I can do with this... Need to get emerald to build first

**Comment by gagarin55** [comment]
@tapdancemobile 
`npm install`
then in one terminal `npm run build:all` and `npm run start:electron` in another.
contact me at gitter if you have issues - https://gitter.im/ethereumproject/emerald-wallet

PS. unfortunately I haven't received my Ledger yet

**Comment by tapdancemobile** [comment]
I have emerald building - What is expected behaviour? You plug the nano in and use it to verify the transaction? Does the ETC account need to be one managed by the ledger? I'm not sure I understand the order of operations here

**Comment by tapdancemobile** [comment]
Ok, so when I connect my ledger It shows the list of etc addresses but with each address it seems to log this when rendering it `[16:17:01.865] [error] Failed to get Ledger connection TypeError: _api.api.geth.call is not a function
    at file:///Users/macuser/Projects/Crypto/emerald-wallet/app/index.js:18822:23
    at file:///Users/macuser/Projects/Crypto/emerald-wallet/app/index.js:143494:18
    at dispatch (file:///Users/macuser/Projects/Crypto/emerald-wallet/app/index.js:143549:18)
    at file:///Users/macuser/Projects/Crypto/emerald-wallet/app/index.js:18849:13
    at <anonymous>`

Also, when I select an address to import into the emerald wallet and manage from my ledger it freezes and give me this error in the log: `[16:17:16.834] [info] Import Ledger address { address: 'e892EfCBbF5b0b569717e3642308f32814e6BE81',
  crypto: 
   { cipher: 'hardware',
     hardware: 'ledger-nano-s:v1',
     hd_path: '44\'/61\'/0\'/0/0' },
  id: 'c9d4d01e-5240-4891-be21-0c9a0b59ade5',
  name: 'Ledger 44\'/61\'/0\'/0/0',
  version: 3 }
[16:17:17.016] [debug] screen - Show screen:  account
[16:17:17.028] [warn] AccountShow - Can't find account in general list of accounts 0xe892EfCBbF5b0b569717e3642308f32814e6BE81 null`

**Comment by splix** [comment]
When you import an address there is an option to use address manager by Ledger. That means that Wallet will show addr and corresponding transactions, but when you'll try to send a transaction it will ask you to sign it with ledger. You probably figured it out already. I had error at that form, when you click "Send" button, I expect that Ledger will ask for a confirmation, but it never happen. It maybe related to type of RPC node, because it was working with local Geth, but stopped to work after switching to a remote node.

`_api.api.geth.call is not a function` strange error, @gagarin55 do you have any idea?

And yeah, it seems that redux is messed (probably it didn't update state after importing new addr)

**Comment by tapdancemobile** [comment]
Getting this upon attempting to add the address to emerald... from the chrome debug log:
`index.js:635 Uncaught Error: Attempted to update component `TokenBalances` that has already been unmounted (or failed to mount).
    at invariant (index.js:635)
    at ReactCompositeComponentWrapper.updateComponent (index.js:127329)
    at ReactCompositeComponentWrapper.receiveComponent (index.js:127292)
    at Object.receiveComponent (index.js:18017)
    at Object.updateChildren (index.js:126668)
    at ReactDOMComponent._reconcilerUpdateChildren (index.js:131404)
    at ReactDOMComponent._updateChildren (index.js:131508)
    at ReactDOMComponent.updateChildren (index.js:131495)
    at ReactDOMComponent._updateDOMChildren (index.js:128709)
    at ReactDOMComponent.updateComponent (index.js:128523)`

**Comment by tapdancemobile** [comment]
also, `index.js:61616 Uncaught (in promise) TypeError: Cannot read property 'map' of undefined
    at TokenBalances (index.js:61616)
    at index.js:127051
    at measureLifeCyclePerf (index.js:126821)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (index.js:127050)
    at ReactCompositeComponentWrapper._constructComponent (index.js:127025)
    at ReactCompositeComponentWrapper.mountComponent (index.js:126933)
    at Object.mountComponent (index.js:17938)
    at ReactDOMComponent.mountChildren (index.js:131434)
    at ReactDOMComponent._createInitialChildren (index.js:128466)
    at ReactDOMComponent.mountComponent (index.js:128285)`

**Comment by tapdancemobile** [comment]
I was able to send a tx to bittrex from emerald using my ledger. Couple observations:

- I had to press the `Send` button twice. First time silently errored. 
- Once the tx sent, an alert appeared about `unable to get master node of null`
