### ISSUE TITLE
Binary failed to start: hash mismatch: command not found

### ISSUE THREAD

**Issue by splix** [ethereumproject/emerald-wallet#401]
Can't run app, stuck on startup screen. Found following in logs:
```
Warning: Failed prop type: Invalid prop `total` of type `string` supplied to `Render`, expected `number`.
    in Render (created by Connect(Render))
    in Connect(Render) (created by Header)
    in div (created by Header)
    in div (created by Header)
    in div (created by Header)
    in Header (created by Connect(Header))
    in Connect(Header) (created by Unknown)
    in div (created by Unknown)
    in Unknown (created by Translate(Component))
    in Translate(Component) (created by Connect(Translate(Component)))
    in Connect(Translate(Component)) (created by App)
    in MuiThemeProvider (created by App)
    in Provider (created by App)
    in I18nextProvider (created by App)
    in App
```

**Comment by whilei** [comment]
I may have similar issue:

![screen shot 2017-12-07 at 15 04 55](https://user-images.githubusercontent.com/10228550/33738808-2404b8c2-db60-11e7-8495-b69f550c559a.png)
![screen shot 2017-12-07 at 15 06 53](https://user-images.githubusercontent.com/10228550/33738845-4cd2e134-db60-11e7-8905-14e984f7a638.png)
![screen shot 2017-12-07 at 15 06 58](https://user-images.githubusercontent.com/10228550/33738846-4cf2de12-db60-11e7-9269-7dc0206e5693.png)

```
index.js:689 Warning: Failed prop type: Invalid prop `total` of type `string` supplied to `Render`, expected `number`.
    in Render (created by Connect(Render))
    in Connect(Render) (created by Header)
    in div (created by Header)
    in div (created by Header)
    in div (created by Header)
    in Header (created by Connect(Header))
    in Connect(Header) (created by Unknown)
    in div (created by Unknown)
    in Unknown (created by Translate(Component))
    in Translate(Component) (created by Connect(Translate(Component)))
    in Connect(Translate(Component)) (created by App)
    in MuiThemeProvider (created by App)
    in Provider (created by App)
    in I18nextProvider (created by App)
    in App
index.js:147113  action @ 15:04:45.907 LAUNCHER/CONFIG
index.js:147125  prev state Object
index.js:147129  action Object
index.js:147137  next state Object
index.js:147113  action @ 15:04:45.972 ACCOUNT/SET_LOCALE_CURRENCY
index.js:147125  prev state Object
index.js:147129  action Object
index.js:147137  next state Object
index.js:147113  action @ 15:04:45.980 SETTINGS/SET_SHOW_HIDDEN_ACCOUNTS
index.js:147125  prev state Object
index.js:147129  action Object
index.js:147137  next state Object
index.js:147113  action @ 15:04:45.985 SCREEN/OPEN
index.js:147125  prev state Object
index.js:147129  action Object
index.js:147137  next state Object
index.js:147113  action @ 15:04:45.990 LEDGER/WATCH
index.js:147125  prev state Object
index.js:147129  action Object
index.js:147137  next state Object
index.js:79931 [15:04:45.699] index - Starting Emerald Wallet...
index.js:147113  action @ 15:04:47.572 LAUNCHER/SERVICE_STATUS
index.js:147125  prev state Object
index.js:147129  action Object
index.js:147137  next state Object
index.js:147113  action @ 15:04:47.574 LAUNCHER/SERVICE_STATUS
index.js:147125  prev state Object
index.js:147129  action Object
index.js:147137  next state Object
index.js:79931 [15:04:51.320] Unable to download Geth Error: hash mismatch
    at /Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/kbpgp/lib/rsa.js:649:110
    at Deferrals.exports.Deferrals.Deferrals._call (/Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/iced-runtime/lib/runtime.js:86:16)
    at /Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/iced-runtime/lib/runtime.js:98:26
    at trampoline (/Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/iced-runtime/lib/runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (/Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/iced-runtime/lib/runtime.js:96:16)
    at /Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/kbpgp/lib/rsa.js:644:32
    at /Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/kbpgp/lib/rsa.js:645:15
    at Pair.verify_unpad_and_check_hash (/Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/kbpgp/lib/rsa.js:655:15)
    at /Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/kbpgp/lib/openpgp/packet/signature.js:516:25
    at _this.key_manager.pgp_check_not_expired.subkey_material (/Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/kbpgp/lib/openpgp/packet/signature.js:529:15)

(anonymous) @ index.js:79931
index.js:147113  action @ 15:04:51.324 LAUNCHER/MESSAGE
index.js:147125  prev state Object
index.js:147129  action Object
index.js:147137  next state Object
index.js:79931 [15:04:51.321] Failed to start Services: Error: hash mismatch
    at /Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/kbpgp/lib/rsa.js:649:110
    at Deferrals.exports.Deferrals.Deferrals._call (/Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/iced-runtime/lib/runtime.js:86:16)
    at /Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/iced-runtime/lib/runtime.js:98:26
    at trampoline (/Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/iced-runtime/lib/runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (/Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/iced-runtime/lib/runtime.js:96:16)
    at /Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/kbpgp/lib/rsa.js:644:32
    at /Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/kbpgp/lib/rsa.js:645:15
    at Pair.verify_unpad_and_check_hash (/Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/kbpgp/lib/rsa.js:655:15)
    at /Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/kbpgp/lib/openpgp/packet/signature.js:516:25
    at _this.key_manager.pgp_check_not_expired.subkey_material (/Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/kbpgp/lib/openpgp/packet/signature.js:529:15)
```

**Comment by whilei** [comment]
HOWEVER, after a single restart it works fine.

**Comment by shanejonas** [comment]
the react proptype stuff is just warnings. the real error here is with `npm run getemerald` -> `hash mismatch: command not found`, maybe try re-running `npm install`?

**Comment by shanejonas** [comment]
we talked about it in hangouts. not really sure that `npm run getemerald` is the problem, @whilei said it happens with the binary build

**Comment by whilei** [comment]
Going to update the issue title to reflect the `hash mismatch` error instead then.

**Comment by shanejonas** [comment]
this was an issue with the build. has been fixed since. i'll try to find the PR that fixed it
