### ISSUE TITLE
Local geth doesn't start during first run

### ISSUE THREAD

**Issue by gagarin55** [ethereumproject/emerald-wallet#422]
After removing `settings.json` if `geth` already presented in wallet dir error occurs

```

[14:51:13.790] [info] Can't find existing RPC. Try to launch
[14:51:14.106] [error] Unable to download Geth Error: File geth exists
    at /home/k2/Downloads/EmeraldWallet-linux-v0.7.0+23-3b85e58/resources/app.asar/node_modules/emerald-js/lib/download/downloader.js:112:22
    at <anonymous>

[14:51:14.106] [error] Failed to restart after changing settings Error: File geth exists
    at /home/k2/Downloads/EmeraldWallet-linux-v0.7.0+23-3b85e58/resources/app.asar/node_modules/emerald-js/lib/download/downloader.js:112:22
    at <anonymous>
```

**Comment by j-chimienti** [comment]
Yes, same issue.

I was able to start application on first run.

Second run failed. I removed settings.json

```


[09:12:28.814] [debug] launcherActions - Got launcher config from electron: {"version":1,"geth":{"url":"http://127.0.0.1:8545","type":"local"},"chain":{"id":61,"name":"mainnet"},"terms":"v1"}

message { mode: 
   { status: 'not ready',
     type: 'local',
     url: 'http://127.0.0.1:8545' },
  service: 'geth' }

```

**Comment by gagarin55** [comment]
Fixed in https://github.com/ethereumproject/emerald-wallet/pull/423
