### ISSUE TITLE
Cannot withdraw from Emerald Wallet

### ISSUE THREAD

**Issue by PandaHanda** [ethereumproject/emerald-wallet#472]
Keep getting this error message:
Invalid params: Invalid bytes format. Expected a 0x-prefixed hex string with even length.

I've tried withdrawing to two different addresses, same error.

Thanks for your help

**Comment by splix** [comment]
does your address starts with `0x` and has 40 symbols `a-zA-Z0-9` in it?

**Comment by PandaHanda** [comment]
This is my address with the ETC:

0x391e8fe46a85bd80cd34269622dc48f2d22cc2ad

This is one of the addresses I tried sending ETC to:
0x6ffA3b30bE7595fFB3582b0C9D88E3Bed7f6646A

**Comment by splix** [comment]
Yes, that's a valid address, it should work. At which point you get this error?

**Comment by PandaHanda** [comment]
When I click send, I get the error immediately

**Comment by PandaHanda** [comment]
I am on mainnet epool.io, does that make a difference?

**Comment by gagarin55** [comment]
@PandaHanda  Could you please provide more information, what OS is and logs details

**Comment by PandaHanda** [comment]
Version 0.6.0 1122

My OS High Sierra 10.13

What logs?

**Comment by PandaHanda** [comment]
Still getting the error, even after adjusting the amount I am trying to send. I found this on the about page... 0.7.0 RC 1

If you tell me where to find the logs, I can send them. I'd rather not get caught with all my ETC stuck in a wallet if the market seriously goes down... thanks

**Comment by splix** [comment]
If you urgently need to move your funds you can export your private key and export it in another wallet, such as MyEtherWallet (but be careful, there're many fake MyEtherWallet clones)

**Comment by PandaHanda** [comment]
Perfect!! You are a lifesaver. Thanks for all your help :)

**Comment by pcdinh** [comment]
I am using Ethereum Classic Wallet 0.7 RC1. Same issue. 

>> Invalid params: Invalid bytes format. Expected a 0x-prefixed hex string with even length.

I found the following log:

[2018-02-05 03:22:11.777] [debug] CreateTx - {"from":"0xa312ea325c9f520d58acfaf81786d929ad9ca896","gasPrice":"0x04a817c800","gas":"0x5208","to":"0x2813bcc9dd9918142884d486bff0e5d310527dfe","value":"0x0de0b6b3a7640000","data":""}
[2018-02-05 03:22:12.047] [error] CreateTx - Validation failure JsonRpcError: Invalid params: Invalid bytes format. Expected a 0x-prefixed hex string with even length.
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/pcdinh/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:23991:30)
    at new JsonRpcError (file:///C:/Users/pcdinh/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:24020:116)
    at file:///C:/Users/pcdinh/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:24057:19
    at <anonymous>
[2018-02-05 03:22:12.204] [warn] Failed to connect to Ledger undefined
[2018-02-05 03:22:13.228] [warn] Failed to connect to Ledger undefined
[2018-02-05 03:22:16.269] [warn] Failed to connect to Ledger undefined
[2018-02-05 03:22:17.289] [warn] Failed to connect to Ledger undefined

**Comment by gagarin55** [comment]
@pcdinh Switch to gastracker.io Mainnet endpoint, looks like epool.io host new Parity and it has issue, we will fix it asap
