### ISSUE TITLE
Failed to start Services: Error: Not Connected

### ISSUE THREAD

**Issue by tetraceneTV** [ethereumproject/emerald-wallet#497]
Failed to start Services: Error: Not Connected

I can't get my wallet to open, anyone know how to fix this?

index.js:17914 i18next: languageChanged en-US
index.js:17914 i18next: initialized Object
index.js:38745 Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
printWarning @ index.js:38745
index.js:154225  action @ 10:38:31.870 LAUNCHER/CONFIG
index.js:154237  prev state Object
index.js:154241  action Object
index.js:154249  next state Object
index.js:154225  action @ 10:38:31.892 ACCOUNT/SET_LOCALE_CURRENCY
index.js:154237  prev state Object
index.js:154241  action Object
index.js:154249  next state Object
index.js:154225  action @ 10:38:31.896 SETTINGS/SET_SHOW_HIDDEN_ACCOUNTS
index.js:154237  prev state Object
index.js:154241  action Object
index.js:154249  next state Object
index.js:154225  action @ 10:38:31.899 SCREEN/OPEN
index.js:154237  prev state Object
index.js:154241  action Object
index.js:154249  next state Object
index.js:154225  action @ 10:38:31.901 LEDGER/WATCH
index.js:154237  prev state Object
index.js:154241  action Object
index.js:154249  next state Object
index.js:82407 [10:38:31.471] geth process exited with code: 1
(anonymous) @ index.js:82407
index.js:154225  action @ 10:38:31.936 LAUNCHER/SERVICE_STATUS
index.js:154237  prev state Object
index.js:154241  action Object
index.js:154249  next state Object
index.js:82407 [10:38:31.761] index - Starting Emerald Wallet...
index.js:154225  action @ 10:38:33.627 LAUNCHER/SERVICE_STATUS
index.js:154237  prev state Object
index.js:154241  action Object
index.js:154249  next state Object
index.js:154225  action @ 10:38:33.627 LAUNCHER/SERVICE_STATUS
index.js:154237  prev state Object
index.js:154241  action Object
index.js:154249  next state Object
index.js:82407 [10:39:01.057] Failed to start Services: Error: Not Connected
    at checker.exists.then.catch (/Applications/Cryptocurrency/EmeraldWallet.app/Contents/Resources/app.asar/electron/nodecheck.js:21:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by gagarin55** [comment]
Did you resolve your issue ? Could you provide any [logs](https://github.com/ethereumproject/emerald-wallet#logs) ?

**Comment by tetraceneTV** [comment]
Hey, it was just a matter of restarting the computer and that fixed it.

Thanks!
